### ISSUE TITLE
Not showing dashboard page

### ISSUE THREAD

**Issue by B0B81** [edwardspresume/sveltekit-lucia-auth-v3-example#3]
Hi Edwardspresume, thanks for sharing your experience with lucia. After cloning the main branch and install with pnpm install etc. I wanted to test registration an so on. After registering the page redirects to /dashboard. There I can se a milisecond the Dashboard but then I see the Register form. Maybe the routing has an error.

**Comment by edwardspresume** [comment]
Hi Bob, 

Np and ok i'll look into the issue either later today or tomorrow

**Comment by B0B81** [comment]
Hi, I cloned your new branch password_reset an everything works fine. Clone your main branch again an routing just works fine. Very strange.

**Comment by edwardspresume** [comment]
That is strange, but I am glad that everything is working now

**Comment by aabbtree77** [comment]
Still the same problem here.

I am testing the email verification branch, the code works fine on Firefox 123, but it is not possible to get into Dashboard on Chrome 115. This could be due to sveltekit and browser incompatibilities, not this code. 

On Chrome 115 (Ubuntu 22.04):

Local:   http://localhost:5173/ - Loads the landing page, impossible to even get into the registration form, but it loads it briefly when pressing on the button and during refreshing of the browser.

Network: http://192.168.0.101:5173/ - Shows the registration form, but no email verification prompt follows, even if the email is sent.

Everything works fine on Firefox 123, except in one case (cannot remember exact action sequence) I could see the console errors with F12 around http vs https cookie (will post this in a separate issue).

Also, only on Chrome 115 sometimes I can see the warning in F12 console: 

<Page> received an unexpected slot "default".

There are a lot of these slot warnings and errors in the sveltekit issues on github, don't know what to do about it, they do not show on Firefox 123.
